esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    # type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan

logger:

# Base Device Functionality.
#button:
#  - platform: safe_mode
#    id: button_safe_mode
#    name: Safe Mode Boot
#
#  - platform: factory_reset
#    id: factory_reset_btn
#    name: Factory reset
